apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgerock-deploy
  labels:
    app: forgerock_stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgerock
  template:
    metadata:
      labels:
        app: forgerock
    spec:
      containers:
      - name: forgerock
        image: jangetta/forgerock_stock:0.1
        ports:
        - containerPort: 8081
        env:
        - name: stonks
          valueFrom:
            configMapKeyRef:
              name: stock.yaml
              key: SYMBOL
        - name: days
          valueFrom:
            configMapKeyRef:
              name: stock.yaml
              key: NDAYS
        - name: secret_api
          valueFrom:
            secretKeyRef:
              name: forgerock-secret
              key: secret-token
