apiVersion: v1
kind: Service
metadata:
  name: forgerock-ingress
  labels:
    app: forgerock
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app: forgerock-stock

